# Generated by Django 5.0.6 on 2024-06-19 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefingRaoaLessoniaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao_operacao', models.TextField(blank=True, null=True, verbose_name='Descrição da Operação')),
                ('infra_critica_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Infra Crítica Brasília')),
                ('infra_critica_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Infra Crítica Rio de Janeiro')),
                ('gcn_tcr_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='GCN/TCR Brasília')),
                ('gcn_tcr_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='GCN/TCR Rio de Janeiro')),
                ('clima_espacial', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Clima Espacial')),
                ('ssa_sda', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SSA/SDA')),
            ],
        ),
    ]
