# Generated by Django 5.0.6 on 2024-06-19 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('lote_7_planejado', models.IntegerField(verbose_name='Lote 7 Planejado')),
                ('iceye_planejado', models.IntegerField(verbose_name='ICEYE Planejado')),
                ('lote_7_recebido', models.IntegerField(verbose_name='Lote 7 Recebido')),
                ('iceye_recebido', models.IntegerField(verbose_name='ICEYE Recebido')),
            ],
        ),
    ]
