# Generated by Django 5.0.6 on 2024-06-19 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraestruturaCritica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('gmg1_1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 1.1 Brasília')),
                ('gmg1_1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 1.1 Rio de Janeiro')),
                ('gmg1_2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 1.2 Brasília')),
                ('gmg1_2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 1.2 Rio de Janeiro')),
                ('autonomia1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Autonomia 1 Brasília')),
                ('autonomia1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Autonomia 1 Rio de Janeiro')),
                ('ups1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='UPS 1 Brasília')),
                ('ups1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='UPS 1 Rio de Janeiro')),
                ('gmg2_1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 2.1 Brasília')),
                ('gmg2_1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 2.1 Rio de Janeiro')),
                ('gmg2_2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 2.2 Brasília')),
                ('gmg2_2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='GMG 2.2 Rio de Janeiro')),
                ('autonomia2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Autonomia 2 Brasília')),
                ('autonomia2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Autonomia 2 Rio de Janeiro')),
                ('ups2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='UPS 2 Brasília')),
                ('ups2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='UPS 2 Rio de Janeiro')),
                ('url1_1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 1.1 Brasília')),
                ('url1_1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 1.1 Rio de Janeiro')),
                ('url1_2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 1.2 Brasília')),
                ('url1_2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 1.2 Rio de Janeiro')),
                ('url2_1_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 2.1 Brasília')),
                ('url2_1_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 2.1 Rio de Janeiro')),
                ('url2_2_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 2.2 Brasília')),
                ('url2_2_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='URL 2.2 Rio de Janeiro')),
                ('combate_incendio_brasilia', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Combate a Incêndio Brasília')),
                ('combate_incendio_rio', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Combate a Incêndio Rio de Janeiro')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
