# Generated by Django 5.0.6 on 2024-06-19 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaEspacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('maior_k_24h', models.FloatField(verbose_name='Maior K nas últimas 24h')),
                ('maior_k_previsto', models.FloatField(verbose_name='Maior K previsto até D+2')),
                ('tempestade_solar_prevista', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Tempestade Solar Prevista')),
            ],
        ),
    ]
