# Generated by Django 5.0.6 on 2024-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('admin', 'Admin'), ('sgdc', 'SGDC'), ('lessonia', 'Lessonia'), ('infraestruturas_criticas', 'Infraestruturas Críticas')], default='sgdc', max_length=25),
        ),
    ]
