# Generated by Django 5.0.6 on 2024-06-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('admin', 'Admin'), ('sgdc', 'SGDC'), ('lessonia', 'Lessonia'), ('infraestrutura_critica', 'Infraestruturas Críticas')], default='sgdc', max_length=25),
        ),
    ]
