# Generated by Django 5.0.6 on 2024-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saude_plataforma_x18', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Saúde da Plataforma X18')),
                ('saude_plataforma_x19', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Saúde da Plataforma X19')),
                ('alerta_conjuncao_x18', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Alerta de Conjunção X18')),
                ('alerta_conjuncao_x19', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Alerta de Conjunção X19')),
                ('manobra_x18', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Manobra X18')),
                ('manobra_x19', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, verbose_name='Manobra X19')),
                ('passes_brasilia_x18', models.IntegerField(verbose_name='Passes Brasília X18')),
                ('passes_brasilia_x19', models.IntegerField(verbose_name='Passes Brasília X19')),
                ('passes_formosa_x18', models.IntegerField(verbose_name='Passes Formosa X18')),
                ('passes_formosa_x19', models.IntegerField(verbose_name='Passes Formosa X19')),
                ('passes_manaus_x18', models.IntegerField(verbose_name='Passes Manaus X18')),
                ('passes_manaus_x19', models.IntegerField(verbose_name='Passes Manaus X19')),
                ('antena_brasilia_x18', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Brasília X18')),
                ('antena_brasilia_x19', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Brasília X19')),
                ('antena_formosa_x18', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Formosa X18')),
                ('antena_formosa_x19', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Formosa X19')),
                ('antena_manaus_x18', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Manaus X18')),
                ('antena_manaus_x19', models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10, verbose_name='Antena Manaus X19')),
                ('imagens_planejadas_x18', models.IntegerField(verbose_name='Imagens Planejadas X18')),
                ('imagens_planejadas_x19', models.IntegerField(verbose_name='Imagens Planejadas X19')),
                ('imagens_recebidas_x18', models.IntegerField(verbose_name='Imagens Recebidas X18')),
                ('imagens_recebidas_x19', models.IntegerField(verbose_name='Imagens Recebidas X19')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
