# Generated by Django 5.0.6 on 2024-06-17 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
