# Generated by Django 5.0.6 on 2024-06-23 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing_raoa_sgdc', '0002_alter_briefingraoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefingraoa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
