# Generated by Django 5.0.6 on 2024-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacialSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma_saude', models.CharField(max_length=100)),
                ('proc_executados', models.IntegerField()),
                ('alerta_conjuncao', models.BooleanField(default=False)),
                ('campanha_ranging', models.BooleanField(default=False)),
                ('prox_manobra', models.DateTimeField()),
                ('tempo_eclipse', models.DurationField()),
            ],
        ),
    ]
