# Generated by Django 5.0.6 on 2024-06-19 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacialsegment',
            name='antena_teatro_em_uso',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Antena Teatro em Uso'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='clima_espacial',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Clima Espacial'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='cmc_brasilia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='CMC-x Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='cmc_rio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='CMC-x Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='descricao_operacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Operação'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='enlaces_ativos',
            field=models.IntegerField(default=0, verbose_name='Enlaces Ativos'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='gcn_tcr_brasilia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='GCN/TCR Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='gcn_tcr_rio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='GCN/TCR Rio de Janeiro'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='infra_critica_brasilia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Infra Crítica Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='infra_critica_rio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Infra Crítica Rio de Janeiro'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='qualidade_enlaces',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Qualidade dos Enlaces'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='smc_brasilia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SMC Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='smc_rio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SMC Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='ssa_sda',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SSA/SDA'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='tcr_brasilia',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Antena (TCR) Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='tcr_rio',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Antena (TCR) Rio'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='alerta_conjuncao',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='campanha_ranging',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='plataforma_saude',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='proc_executados',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='prox_manobra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='espacialsegment',
            unique_together={('data',)},
        ),
    ]
