# Generated by Django 5.0.6 on 2024-06-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacialsegment',
            name='alerta_conjuncao',
            field=models.CharField(choices=[(True, 'Sim'), (False, 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='campanha_ranging',
            field=models.CharField(choices=[(True, 'Sim'), (False, 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='plataforma_saude',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
    ]
