# Generated by Django 5.0.6 on 2024-06-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0002_alter_espacialsegment_alerta_conjuncao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacialsegment',
            name='alerta_conjuncao',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='campanha_ranging',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='proc_executados',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=100),
        ),
    ]
