# Generated by Django 5.0.6 on 2024-06-15 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0003_alter_espacialsegment_alerta_conjuncao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacialsegment',
            name='antena_teatro_em_uso',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3, verbose_name='Antena Teatro em Uso'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='cmc_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='CMC-x Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='cmc_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='CMC-x Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='enlaces_ativos',
            field=models.IntegerField(default=0, verbose_name='Enlaces Ativos'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='qualidade_enlaces',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Qualidade dos Enlaces'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='smc_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SMC Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='smc_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='SMC Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='tcr_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Antena (TCR) Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='tcr_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='OK', max_length=100, verbose_name='Antena (TCR) Rio'),
        ),
        migrations.AlterUniqueTogether(
            name='espacialsegment',
            unique_together={('data',)},
        ),
    ]
