# Generated by Django 5.0.6 on 2024-06-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0004_espacialsegment_antena_teatro_em_uso_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='espacialsegment',
            unique_together=set(),
        ),
    ]
