# Generated by Django 5.0.6 on 2024-06-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0005_alter_espacialsegment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='espacialsegment',
            unique_together={('data',)},
        ),
    ]
