# Generated by Django 5.0.6 on 2024-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0006_alter_espacialsegment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacialsegment',
            name='plataforma_saude',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical')], max_length=10),
        ),
    ]
