# Generated by Django 5.0.6 on 2024-06-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0007_alter_espacialsegment_plataforma_saude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacialsegment',
            name='prox_manobra',
            field=models.CharField(max_length=100),
        ),
    ]
