# Generated by Django 5.0.6 on 2024-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgdc', '0009_espacialsegment_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacialsegment',
            name='clima_espacial',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Clima Espacial'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='descricao_operacao',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=200, verbose_name='Descrição da Operação'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='gcn_tcr_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='GCN/TCR Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='gcn_tcr_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='GCN/TCR Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='infra_critica_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Infra Crítica Brasília'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='infra_critica_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Infra Crítica Rio'),
        ),
        migrations.AddField(
            model_name='espacialsegment',
            name='ssa_sda',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='SSA/SDA'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='alerta_conjuncao',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='campanha_ranging',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='cmc_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='CMC-x Brasília'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='cmc_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='CMC-x Rio'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='plataforma_saude',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='proc_executados',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='qualidade_enlaces',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Qualidade dos Enlaces'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='smc_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='SMC Brasília'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='smc_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='SMC Rio'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='tcr_brasilia',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Antena (TCR) Brasília'),
        ),
        migrations.AlterField(
            model_name='espacialsegment',
            name='tcr_rio',
            field=models.CharField(choices=[('OK', 'OK'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('NORMAL', 'Normal')], default='OK', max_length=100, verbose_name='Antena (TCR) Rio'),
        ),
    ]
